# application configuration
[application]
codebase_path = "codebase"
ignored_paths = [
    '__pycache__',
    '.git',
    'classes',
    'test-classes'
]
ignored_extensions=[
    '.png',
    '.jpeg',
    '.pyc',
    '.gem'
]